###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'L. Grobol'
bibtex_bibfiles = ['references.bib']
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_proof', 'jupyterlite_sphinx', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = 'favicon.svg'
html_logo = 'logo.svg'
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {'repository_provider': 'custom'}
html_title = 'Mathématiques pour le TAL'
jupyterlite_contents = ['chapters']
language = 'fr'
latex_additional_files = ['latex_extra.sty']
latex_elements = {'fontpkg': '\\settmainfont[\n  UprightFont={* Regular},\n  ItalicFont={* Italic},\n  BoldFont={* Bold},\n  BoldItalicFont={* Bold Italic},\n]{Libertinus Serif}\n\\setsansfont{Libertinus Sans}\n\\setmonofont[Scale=MatchLowercase]{Fira Mono}\n', 'papersize': 'a4paper'}
latex_engine = 'lualatex'
mathjax3_config = {'loader': {'load': ['[unicodeMath]/unicode-math.js'], 'paths': {'unicodeMath': 'https://cdn.jsdelivr.net/npm/@amermathsoc/mathjax-unicode-math@1.4/browser'}}, 'tex': {'packages': {'[+]': ['unicode-math']}}}
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'force'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
